### ISSUE TITLE
Docker Compose - Potter Migration Depends on Thor_DB

### ISSUE THREAD

**Issue by commitBlob** [agiliq/building-multi-tenant-applications-with-django#32]
Looking at the docker-compose file I noticed that `potter_migration` depends on `thor_db`.
I'm assuming this is not intentional and it should rather depend on the `potter_db`?

```
  potter_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=potter
      - POSTGRES_USER=potter
      - POSTGRES_DB=potter
  potter_web:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - potter_db
    environment:
      - DATABASE_URL=postgres://potter:potter@potter_db/potter

  potter_migration:
    image: agiliq/multi-tenant-demo
    command: python3 manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - thor_db <---- should be potter_db?
    environment:
      - DATABASE_URL=postgres://potter:potter@potter_db/potter

```
